project:
  type: website
  output-dir: _site
  render:
  - "*.qmd"
  - "!*.md"
execute:
  freeze: auto
author:
  - name: Evan Nelson
    email: nelson01@allegheny.edu
website:
  title: "WorkoutEvaluator: IOS app that provides personalized exercise feedback through user-inputted information"
  navbar:
    right:
      - text: "Senior Thesis"
        href: thesis/index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: journal
    css: styles.css
